{
 "title": "DigiBoard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes",
     "legendFormat": "Total RAM {{instance}}"
    },
    {
     "expr": "windows_cs_physical_memory_bytes- windows_os_physical_memory_free_bytes",
     "legendFormat": "RAM Usage {{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " sum by(instance) (rate(windows_process_cpu_time_total{process!~\"Idle\"}[2m]))\r\n / on(instance) group_left sum by(instance) (rate(windows_cpu_time_total{process!~\"Idle\"}[2m]))",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "Max" }
   ]
  },
  { "title": "RabbitMQ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RabbitMQ Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue!~\"nsb.delay-level-.+\",queue!~\".*(error|instance-1)$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "RabbitMQ Error Queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\".*error$\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Nservicebus Delay queues",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue=~\"nsb.delay-level-.+\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}