{
 "title": "DigiBoard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "windows_cs_physical_memory_bytes",
       "legendFormat": "Total RAM {{instance}}"
      },
      {
       "expr": "windows_cs_physical_memory_bytes- windows_os_physical_memory_free_bytes",
       "legendFormat": "RAM Usage {{instance}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": " sum by(instance) (rate(windows_process_cpu_time_total{process!~\"Idle\"}[2m]))\r\n / on(instance) group_left sum by(instance) (rate(windows_cpu_time_total{process!~\"Idle\"}[2m]))",
       "legendFormat": "{{instance}}"
      },
      { "expr": "1", "legendFormat": "Max" }
     ]
    },
    {
     "title": "Used disk space",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - windows_logical_disk_free_bytes / windows_logical_disk_size_bytes ",
       "legendFormat": "{{volume}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "RabbitMQ Queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages_ready{queue!~\"nsb.delay-level-.+\",queue!~\".*(error|instance-1)$\"}",
       "legendFormat": "{{queue}}"
      }
     ]
    },
    {
     "title": "RabbitMQ Error Queues",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages_ready{queue=~\".*error$\"}",
       "legendFormat": "{{queue}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Debouncing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Debouncing Messages",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "debouncing_waiting_messages", "legendFormat": "Waiting Messages" },
      {
       "expr": "debouncing_waiting_messages_exceeded",
       "legendFormat": "Delayed Messages"
      }
     ]
    },
    {
     "title": "Debouncing Behind",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "debouncing_waiting_messages_worst_behind_seconds",
       "legendFormat": "How much behind"
      }
     ]
    },
    {
     "title": "Debouncing Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short", "label": "Messages/second" }
     ],
     "targets": [
      {
       "expr": "rate(debouncing_inbound_total[2m])",
       "legendFormat": "Inbound {{instance}}"
      },
      {
       "expr": "rate(debouncing_outbound_total[2m])",
       "legendFormat": "Outbound {{instance}}"
      }
     ]
    },
    {
     "title": "Alive cores services",
     "type": "graph",
     "description": "How many of the core services are currently alive",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (up{service_name=~\".+\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Search duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (search_name, le) (rate(digizuite_damcenter_search_duration_seconds_bucket[5m])))",
     "legendFormat": "{{search_name}}"
    }
   ]
  },
  {
   "title": "Batch Update Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(digizuite_damcenter_batch_update_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "BatchUpdate"
    }
   ]
  },
  {
   "title": "Replace asset calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(digizuite_damcenter_replace_asset_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Initiate Upload calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(digizuite_damcenter_initiate_upload_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Search count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (search_name) (digizuite_damcenter_search_duration_seconds_count)",
     "legendFormat": "{{search_name}}"
    }
   ]
  },
  {
   "title": "Batch Update request per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(digizuite_damcenter_batch_update_duration_seconds_count[1m])",
     "legendFormat": "Requests per second"
    }
   ]
  },
  {
   "title": "Upload Asset calls",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(digizuite_damcenter_upload_asset_duration_seconds_count[1m])"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Automation job duration",
   "type": "graph",
   "description": "The name of each line is the id of the automation",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(jobcruncher_workflow_duration_seconds_bucket[1m])) by (le,workflow_id))",
     "legendFormat": "{{workflow_id}}"
    }
   ]
  }
 ]
}